import type { Assignment, DashboardAnalytics, Duty, Officer } from "../types/domain";

const today = new Date().toISOString().slice(0, 10);
const yesterday = new Date(Date.now() - 86400000).toISOString().slice(0, 10);

export const mockOfficers: Officer[] = [
  {
    id: 1,
    name: "Asha Rao",
    belt_number: "PC-1001",
    rank: "Constable",
    station: "Central",
    mobile_number: "9999999999",
    gender: "Female",
    department_unit: "Traffic",
    joining_date: "2022-01-15",
    availability_status: "Available",
    is_active: true,
    weekly_hours: 0,
    monthly_hours: 0,
    skills: ["Traffic Control", "First Aid"],
  },
  {
    id: 2,
    name: "Vikram Singh",
    belt_number: "HC-2042",
    rank: "Head Constable",
    station: "Central",
    mobile_number: "9999999998",
    gender: "Male",
    department_unit: "Law and Order",
    joining_date: "2018-07-03",
    availability_status: "Available",
    is_active: true,
    weekly_hours: 0,
    monthly_hours: 0,
    skills: ["Crowd Control"],
  },
  {
    id: 3,
    name: "Meera Patel",
    belt_number: "SI-3011",
    rank: "SI",
    station: "North",
    mobile_number: "9999999997",
    gender: "Female",
    department_unit: "Investigation",
    joining_date: "2016-03-22",
    availability_status: "Training",
    is_active: true,
    weekly_hours: 0,
    monthly_hours: 0,
    skills: ["VIP Security", "Investigation"],
  },
  {
    id: 4,
    name: "Rahul Nair",
    belt_number: "PC-1140",
    rank: "Constable",
    station: "North",
    mobile_number: "9999999996",
    gender: "Male",
    department_unit: "Patrol",
    joining_date: "2021-11-10",
    availability_status: "On Leave",
    is_active: true,
    weekly_hours: 0,
    monthly_hours: 0,
    skills: ["First Aid", "Crowd Control"],
  },
  {
    id: 5,
    name: "Farhan Ali",
    belt_number: "CI-5102",
    rank: "CI",
    station: "West",
    mobile_number: "9999999995",
    gender: "Male",
    department_unit: "Operations",
    joining_date: "2012-09-18",
    availability_status: "Available",
    is_active: true,
    weekly_hours: 0,
    monthly_hours: 0,
    skills: ["Crowd Control", "VIP Security"],
  },
  {
    id: 6,
    name: "Priya Sharma",
    belt_number: "PC-1205",
    rank: "Constable",
    station: "South",
    mobile_number: "9999999994",
    gender: "Female",
    department_unit: "Patrol",
    joining_date: "2023-03-01",
    availability_status: "Available",
    is_active: true,
    weekly_hours: 0,
    monthly_hours: 0,
    skills: ["Traffic Control"],
  },
  {
    id: 7,
    name: "Suresh Kumar",
    belt_number: "HC-2090",
    rank: "Head Constable",
    station: "West",
    mobile_number: "9999999993",
    gender: "Male",
    department_unit: "Law and Order",
    joining_date: "2019-06-15",
    availability_status: "Available",
    is_active: true,
    weekly_hours: 0,
    monthly_hours: 0,
    skills: ["Crowd Control", "First Aid"],
  },
  {
    id: 8,
    name: "Anita Desai",
    belt_number: "SI-3045",
    rank: "SI",
    station: "South",
    mobile_number: "9999999992",
    gender: "Female",
    department_unit: "Investigation",
    joining_date: "2017-08-20",
    availability_status: "Available",
    is_active: true,
    weekly_hours: 0,
    monthly_hours: 0,
    skills: ["Investigation", "First Aid"],
  },
  {
    id: 9,
    name: "Rajan Verma",
    belt_number: "DSP-9001",
    rank: "DSP",
    station: "Central",
    mobile_number: "9999999991",
    gender: "Male",
    department_unit: "Administration",
    joining_date: "2010-01-05",
    availability_status: "Available",
    is_active: true,
    weekly_hours: 0,
    monthly_hours: 0,
    skills: ["VIP Security", "Crowd Control"],
  },
  {
    id: 10,
    name: "Kavitha Reddy",
    belt_number: "PC-1310",
    rank: "Constable",
    station: "North",
    mobile_number: "9999999990",
    gender: "Female",
    department_unit: "Traffic",
    joining_date: "2024-01-10",
    availability_status: "Available",
    is_active: true,
    weekly_hours: 0,
    monthly_hours: 0,
    skills: ["Traffic Control", "First Aid"],
  },
];

export const mockDuties: Duty[] = [
  {
    id: 1,
    duty_name: "Market Patrol",
    duty_type: "Patrol",
    location: "Central Market",
    start_date: today, end_date: today,
    start_time: "08:00:00",
    end_time: "14:00:00",
    shift_type: "Morning",
    required_officers: 2,
    required_rank: "Constable",
    required_skills: ["Traffic Control"],
    priority_level: "High",
    status: "Allocated",
  },
  {
    id: 2,
    duty_name: "VIP Route Security",
    duty_type: "VIP",
    location: "North Avenue",
    start_date: today, end_date: today,
    start_time: "16:00:00",
    end_time: "22:00:00",
    shift_type: "Evening",
    required_officers: 1,
    required_rank: "SI",
    required_skills: ["VIP Security"],
    priority_level: "Critical",
    status: "Allocated",
  },
  {
    id: 3,
    duty_name: "Night Checkpost",
    duty_type: "Checkpost",
    location: "West Bypass",
    start_date: today, end_date: today,
    start_time: "22:00:00",
    end_time: "06:00:00",
    shift_type: "Night",
    required_officers: 3,
    required_rank: "Head Constable",
    required_skills: ["Crowd Control"],
    priority_level: "Medium",
    status: "Allocated",
  },
  {
    id: 4,
    duty_name: "School Zone Traffic",
    duty_type: "Traffic",
    location: "South School Road",
    start_date: today, end_date: today,
    start_time: "08:00:00",
    end_time: "13:00:00",
    shift_type: "Morning",
    required_officers: 1,
    required_rank: "Constable",
    required_skills: ["Traffic Control"],
    priority_level: "Medium",
    status: "Allocated",
  },
  {
    id: 5,
    duty_name: "Festival Ground Security",
    duty_type: "Event",
    location: "Central Ground",
    start_date: today, end_date: today,
    start_time: "14:00:00",
    end_time: "22:00:00",
    shift_type: "Evening",
    required_officers: 4,
    required_rank: "",
    required_skills: ["Crowd Control"],
    priority_level: "High",
    status: "Pending Allocation",
  },
  {
    id: 6,
    duty_name: "Railway Station Watch",
    duty_type: "Surveillance",
    location: "Central Railway Station",
    start_date: today, end_date: today,
    start_time: "06:00:00",
    end_time: "14:00:00",
    shift_type: "Morning",
    required_officers: 2,
    required_rank: "Head Constable",
    required_skills: [],
    priority_level: "High",
    status: "Allocated",
  },
];

export const mockAssignments: Assignment[] = [
  {
    id: 1,
    duty_id: 1,
    officer_id: 1,
    roster_batch_id: 101,
    assignment_date: today,
    start_time: "08:00:00",
    end_time: "14:00:00",
    shift_type: "Morning",
    working_hours: 6,
    is_locked: false,
    officer_name: "Asha Rao",
    belt_number: "PC-1001",
    duty_name: "Market Patrol",
    location: "Central Market",
  },
  {
    id: 2,
    duty_id: 1,
    officer_id: 10,
    roster_batch_id: 101,
    assignment_date: today,
    start_time: "08:00:00",
    end_time: "14:00:00",
    shift_type: "Morning",
    working_hours: 6,
    is_locked: false,
    officer_name: "Kavitha Reddy",
    belt_number: "PC-1310",
    duty_name: "Market Patrol",
    location: "Central Market",
  },
  {
    id: 3,
    duty_id: 2,
    officer_id: 3,
    roster_batch_id: 101,
    assignment_date: today,
    start_time: "16:00:00",
    end_time: "22:00:00",
    shift_type: "Evening",
    working_hours: 6,
    is_locked: false,
    officer_name: "Meera Patel",
    belt_number: "SI-3011",
    duty_name: "VIP Route Security",
    location: "North Avenue",
  },
  {
    id: 4,
    duty_id: 3,
    officer_id: 2,
    roster_batch_id: 101,
    assignment_date: today,
    start_time: "22:00:00",
    end_time: "06:00:00",
    shift_type: "Night",
    working_hours: 8,
    is_locked: false,
    officer_name: "Vikram Singh",
    belt_number: "HC-2042",
    duty_name: "Night Checkpost",
    location: "West Bypass",
  },
  {
    id: 5,
    duty_id: 3,
    officer_id: 7,
    roster_batch_id: 101,
    assignment_date: today,
    start_time: "22:00:00",
    end_time: "06:00:00",
    shift_type: "Night",
    working_hours: 8,
    is_locked: false,
    officer_name: "Suresh Kumar",
    belt_number: "HC-2090",
    duty_name: "Night Checkpost",
    location: "West Bypass",
  },
  {
    id: 6,
    duty_id: 4,
    officer_id: 6,
    roster_batch_id: 101,
    assignment_date: today,
    start_time: "08:00:00",
    end_time: "13:00:00",
    shift_type: "Morning",
    working_hours: 5,
    is_locked: false,
    officer_name: "Priya Sharma",
    belt_number: "PC-1205",
    duty_name: "School Zone Traffic",
    location: "South School Road",
  },
  {
    id: 7,
    duty_id: 6,
    officer_id: 9,
    roster_batch_id: 100,
    assignment_date: yesterday,
    start_time: "06:00:00",
    end_time: "14:00:00",
    shift_type: "Morning",
    working_hours: 8,
    is_locked: true,
    officer_name: "Rajan Verma",
    belt_number: "DSP-9001",
    duty_name: "Railway Station Watch",
    location: "Central Railway Station",
  },
];

export const mockAnalytics: DashboardAnalytics = {
  cards: {
    total_officers: 10,
    available_officers: 7,
    officers_on_leave: 1,
    total_duties_today: 6,
    pending_duties: 1,
    allocated_duties: 5,
    completed_duties: 2,
    fairness_score: 88,
    duty_coverage_percentage: 83,
  },
  weekly_hours: [
    { name: "Asha Rao", hours: 36 },
    { name: "Vikram Singh", hours: 40 },
    { name: "Meera Patel", hours: 30 },
    { name: "Rahul Nair", hours: 8 },
    { name: "Farhan Ali", hours: 34 },
    { name: "Priya Sharma", hours: 25 },
    { name: "Suresh Kumar", hours: 38 },
    { name: "Anita Desai", hours: 32 },
    { name: "Rajan Verma", hours: 42 },
    { name: "Kavitha Reddy", hours: 18 },
  ],
  monthly_hours: [
    { name: "Asha Rao", hours: 148 },
    { name: "Vikram Singh", hours: 162 },
    { name: "Meera Patel", hours: 124 },
    { name: "Rahul Nair", hours: 32 },
    { name: "Farhan Ali", hours: 140 },
    { name: "Priya Sharma", hours: 106 },
    { name: "Suresh Kumar", hours: 156 },
    { name: "Anita Desai", hours: 130 },
    { name: "Rajan Verma", hours: 170 },
    { name: "Kavitha Reddy", hours: 72 },
  ],
  shift_breakdown: [
    { name: "Morning", hours: 112 },
    { name: "Evening", hours: 78 },
    { name: "Night", hours: 64 },
    { name: "Custom", hours: 14 },
  ],
  station_deployment: [
    { name: "Central", count: 18 },
    { name: "North", count: 12 },
    { name: "West", count: 10 },
    { name: "South", count: 8 },
  ],
  rank_deployment: [
    { name: "Constable", count: 22 },
    { name: "Head Constable", count: 14 },
    { name: "SI", count: 8 },
    { name: "CI", count: 4 },
    { name: "DSP", count: 2 },
  ],
  most_utilized: [
    { name: "Rajan Verma", hours: 42 },
    { name: "Vikram Singh", hours: 40 },
    { name: "Suresh Kumar", hours: 38 },
    { name: "Asha Rao", hours: 36 },
    { name: "Farhan Ali", hours: 34 },
  ],
  least_utilized: [
    { name: "Rahul Nair", hours: 8 },
    { name: "Kavitha Reddy", hours: 18 },
    { name: "Priya Sharma", hours: 25 },
    { name: "Meera Patel", hours: 30 },
    { name: "Anita Desai", hours: 32 },
  ],
  overtime: [
    { name: "Rajan Verma", hours: 42 },
    { name: "Vikram Singh", hours: 40 },
    { name: "Suresh Kumar", hours: 38 },
  ],
  under_utilization: [
    { name: "Rahul Nair", hours: 8 },
  ],
};

export const mockHistory = [
  { id: 101, date: today, station: "All", shift_type: "All", fairness_score: 88, is_locked: false, created_at: `${today}T08:15:00` },
  { id: 100, date: yesterday, station: "Central", shift_type: "Morning", fairness_score: 92, is_locked: true, created_at: `${yesterday}T06:30:00` },
  { id: 99, date: yesterday, station: "North", shift_type: "Evening", fairness_score: 85, is_locked: true, created_at: `${yesterday}T14:05:00` },
  { id: 98, date: yesterday, station: "West", shift_type: "Night", fairness_score: 79, is_locked: true, created_at: `${yesterday}T22:00:00` },
];

export const mockUsers = [
  { id: 1, name: "District Admin", email: "admin@drms.local", role: "Admin", station_scope: "All", is_active: true },
  { id: 2, name: "DSP North", email: "dsp@drms.local", role: "DSP", station_scope: "North District", is_active: true },
  { id: 3, name: "CI West", email: "ci.west@drms.local", role: "CI", station_scope: "West", is_active: true },
  { id: 4, name: "SI Central", email: "si.central@drms.local", role: "SI", station_scope: "Central", is_active: true },
  { id: 5, name: "Station Viewer", email: "viewer@drms.local", role: "Viewer", station_scope: "Central", is_active: true },
];

export const mockAuditLogs = [
  { id: 1, action: "create_duty", entity_type: "duty", details: "Market Patrol", created_at: `${today}T07:10:00` },
  { id: 2, action: "create_duty", entity_type: "duty", details: "VIP Route Security", created_at: `${today}T07:12:00` },
  { id: 3, action: "generate_roster", entity_type: "roster_batch", details: "6 assignments created", created_at: `${today}T08:15:00` },
  { id: 4, action: "lock_roster", entity_type: "roster_batch", details: "Morning roster finalized (batch #100)", created_at: `${yesterday}T08:45:00` },
  { id: 5, action: "create_officer", entity_type: "officer", details: "Kavitha Reddy (PC-1310)", created_at: `${yesterday}T09:30:00` },
  { id: 6, action: "set_availability", entity_type: "officer", details: "Rahul Nair → On Leave", created_at: `${yesterday}T10:00:00` },
  { id: 7, action: "generate_roster", entity_type: "roster_batch", details: "4 assignments created (batch #99)", created_at: `${yesterday}T14:05:00` },
  { id: 8, action: "lock_roster", entity_type: "roster_batch", details: "Evening roster finalized (batch #99)", created_at: `${yesterday}T22:30:00` },
];
